mysql:
  host: localhost
  port: 3306
  database: townbuy
  user: root
  password: "password"

towns:
  Moscow:
    mayor: NPC1
    buyable: true
    price: 5
  Petersburg:
    mayor: NPC2
    buyable: false
    price: 0
